# Generated by Django 5.2.4 on 2025-08-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_fee_fee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_status',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='fee_status',
            unique_together={('student', 'month', 'year')},
        ),
    ]
